Logisitc regression to predict absenteeism

import library

In [110]:
import pandas as pd
import numpy as np

In [111]:
data_preproccessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [112]:
data_preproccessed.head()

Reason I  Reason 2  Reason 3  Reason 4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  day  \
0         2     1                          4            7    7   
1         1     0                          0            7   14   
2         0     0                          2            7   15   
3         2     0                          4            7   16   
4         2     1                          2            7   23   

   Day of the week  
0                1  
1                1  
2                2  
3                3  
4                3

#define classes

In [113]:
data_preproccessed['Absenteeism Time in Hours'].median()

3.0

In [114]:
type(data_preproccessed['Absenteeism Time in Hours'])

pandas.core.series.Series

In [115]:
Targets = np.where(data_preproccessed['Absenteeism Time in Hours']> 
                   data_preproccessed['Absenteeism Time in Hours'].median(),1,0)

In [116]:
Targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [117]:
data_preproccessed['Excessive Absenteeism'] = Targets

In [118]:
data_preproccessed.head()

Reason I  Reason 2  Reason 3  Reason 4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  day  \
0         2     1                          4            7    7   
1         1     0                          0            7   14   
2         0     0                          2            7   15   
3         2     0                          4            7   16   
4         2     1                          2            7   23   

   Day of the week  Excessive Absenteeism  
0                1                      1  
1                1                      0  
2                2                      0  
3                3                      1  
4                3                      0

In [119]:
#Comment on the targets

In [120]:
Targets.sum()/ Targets.shape[0]

0.45571428571428574

In [121]:
data_with_targets = data_preproccessed.drop(['Absenteeism Time in Hours'], axis=1)

In [122]:
data_with_targets is data_preproccessed

False

Select the input for the regression

In [123]:
data_with_targets.shape

(700, 17)

In [124]:
data_with_targets.head()

Reason I  Reason 2  Reason 3  Reason 4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Month Value  day  Day of the week  Excessive Absenteeism  
0         2     1            7    7                1                      1  
1         1     0            7   14                1                      0  
2         0     0            7   15                2                      0  
3         2     0            7   16                3                      1  
4         2     1            7   23                3                      0

In [125]:
data_with_targets.iloc[]

SyntaxError: invalid syntax (Temp/ipykernel_24208/2819564722.py, line 1)

In [ ]:
data_with_targets = data_with_targets.drop('day', 1)

C:\Users\Petro\AppData\Local\Temp/ipykernel_24208/634682325.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  data_with_targets = data_with_targets.drop('day', 1)


In [126]:
data_with_targets.head()

Reason I  Reason 2  Reason 3  Reason 4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Month Value  day  Day of the week  Excessive Absenteeism  
0         2     1            7    7                1                      1  
1         1     0            7   14                1                      0  
2         0     0            7   15                2                      0  
3         2     0            7   16                3                      1  
4         2     1            7   23                3                      0

In [127]:
data_with_targets = data_with_targets.drop('Date', 1)

C:\Users\Petro\AppData\Local\Temp/ipykernel_24208/3986029032.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  data_with_targets = data_with_targets.drop('Date', 1)


In [128]:
data_with_targets.head()

Reason I  Reason 2  Reason 3  Reason 4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Month Value  day  Day of the week  Excessive Absenteeism  
0         2     1            7    7                1                      1  
1         1     0            7   14                1                      0  
2         0     0            7   15                2                      0  
3         2     0            7   16                3                      1  
4         2     1            7   23                3                      0

In [129]:
data_with_targets.shape

(700, 16)

In [130]:
data_with_targets.iloc[:,0:-1]

Reason I  Reason 2  Reason 3  Reason 4  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
698         0         0         0         1                     235   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Month Value  day  Day of the week  
0            0         2     1            7    7                1  
1            0         1     0            7   14                1  
2            0         0     0            7   15                2  
3            0         2     0            7   16                3  
4            0         2     1            7   23                3  
..         ...       ...   ...          ...  ...              ...  
695          1         2     0            5   23                2  
696          0         1     2            5   23                2  
697          1         0     0            5   24                3  
698          1         0     0            5   24                3  
699          0         1     1            5   31                3  

[700 rows x 15 columns]

In [131]:
unscaled_inputs = data_with_targets.iloc[:,0:-1]

# Standardize the data

In [132]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [133]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [134]:
 scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [135]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.18272635,
        -1.103121  , -0.68370352],
       [-0.57735027, -0.09298136, -0.31448545, ...,  0.18272635,
        -0.22833658, -0.68370352],
       [-0.57735027, -0.09298136, -0.31448545, ...,  0.18272635,
        -0.10336738, -0.00772546],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.3882935 ,
         1.02135543,  0.66825259],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.3882935 ,
         1.02135543,  0.66825259],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.3882935 ,
         1.89613985,  0.66825259]])

In [136]:
scaled_inputs.shape

(700, 15)

# Split the data into test & train and shuffle 

#import the relevant module

In [137]:
from sklearn.model_selection import train_test_split

#split 

In [138]:
train_test_split(scaled_inputs, Targets)

[array([[ 1.73205081, -0.09298136, -0.31448545, ...,  1.61027597,
         -1.3530594 , -1.35968157],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.95931334,
         -0.9781518 ,  0.66825259],
        [-0.57735027, -0.09298136,  3.17979734, ...,  1.61027597,
         -1.85293621, -0.68370352],
        ...,
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.95931334,
         -0.35330579, -0.68370352],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.10278357,
          0.52147863, -1.35968157],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.67380342,
          0.14657102, -1.35968157]]),
 array([[-0.57735027, -0.09298136,  3.17979734, ..., -1.53033319,
         -0.47827499, -0.68370352],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.95931334,
         -0.47827499, -1.35968157],
        [-0.57735027, -0.09298136, -0.31448545, ...,  0.7537462 ,
          1.52123224, -1.35968157],
        ...,
        [ 1.73205081, -0.09298136, -0.31448545, ...,  

In [139]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, Targets, train_size = 0.8, random_state = 20)

In [140]:
print (x_train.shape, y_train.shape)

(560, 15) (560,)


In [141]:
print (x_test.shape, y_test.shape)

(140, 15) (140,)


# Logistic regression Scikit learning algorithm

In [142]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# training the model

In [143]:
reg = LogisticRegression()

In [146]:
reg.fit(x_train, y_train)

LogisticRegression()

In [149]:
reg.score(x_train, y_train)

0.7839285714285714

In [151]:
## manually check the accuracy

model_outputs = reg.predict(x_train)

model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [152]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [154]:
np.sum(model_outputs == y_train) 

439

In [160]:
model_outputs.shape[0]

560

In [161]:
np.sum(model_outputs == y_train) / model_outputs.shape[0]

0.7839285714285714

In [163]:
shape?

Object `shape` not found.


In [164]:
reg.intercept_

array([-0.22166443])

In [165]:
reg.coef_

array([[ 2.08148228,  0.33562421,  1.56629194,  1.33675975,  0.70531398,
        -0.04081799, -0.20131197, -0.00231068,  0.32013578, -0.13469377,
         0.3831769 , -0.33421837,  0.18827576,  0.02174787, -0.07236916]])

In [168]:
unscaled_inputs.columns.values

array(['Reason I', 'Reason 2', 'Reason 3', 'Reason 4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'day', 'Day of the week'],
      dtype=object)

In [169]:
feature_name = unscaled_inputs.columns.values

In [173]:
summary_table = pd.DataFrame(columns=['Feature name'], data= feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                  Reason I     2.081482
1                  Reason 2     0.335624
2                  Reason 3     1.566292
3                  Reason 4     1.336760
4    Transportation Expense     0.705314
5          Distance to Work    -0.040818
6                       Age    -0.201312
7   Daily Work Load Average    -0.002311
8           Body Mass Index     0.320136
9                 Education    -0.134694
10                 Children     0.383177
11                     Pets    -0.334218
12              Month Value     0.188276
13                      day     0.021748
14          Day of the week    -0.072369

In [174]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.221664
1                  Reason I     2.081482
2                  Reason 2     0.335624
3                  Reason 3     1.566292
4                  Reason 4     1.336760
5    Transportation Expense     0.705314
6          Distance to Work    -0.040818
7                       Age    -0.201312
8   Daily Work Load Average    -0.002311
9           Body Mass Index     0.320136
10                Education    -0.134694
11                 Children     0.383177
12                     Pets    -0.334218
13              Month Value     0.188276
14                      day     0.021748
15          Day of the week    -0.072369

In [175]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [176]:
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -0.221664    0.801184
1                  Reason I     2.081482    8.016343
2                  Reason 2     0.335624    1.398813
3                  Reason 3     1.566292    4.788858
4                  Reason 4     1.336760    3.806689
5    Transportation Expense     0.705314    2.024482
6          Distance to Work    -0.040818    0.960004
7                       Age    -0.201312    0.817657
8   Daily Work Load Average    -0.002311    0.997692
9           Body Mass Index     0.320136    1.377315
10                Education    -0.134694    0.873984
11                 Children     0.383177    1.466938
12                     Pets    -0.334218    0.715897
13              Month Value     0.188276    1.207166
14                      day     0.021748    1.021986
15          Day of the week    -0.072369    0.930187

In [178]:
summary_table.sort_values('Odds_ratio', ascending =False)

Feature name  Coefficient  Odds_ratio
1                  Reason I     2.081482    8.016343
3                  Reason 3     1.566292    4.788858
4                  Reason 4     1.336760    3.806689
5    Transportation Expense     0.705314    2.024482
11                 Children     0.383177    1.466938
2                  Reason 2     0.335624    1.398813
9           Body Mass Index     0.320136    1.377315
13              Month Value     0.188276    1.207166
14                      day     0.021748    1.021986
8   Daily Work Load Average    -0.002311    0.997692
6          Distance to Work    -0.040818    0.960004
15          Day of the week    -0.072369    0.930187
10                Education    -0.134694    0.873984
7                       Age    -0.201312    0.817657
0                 Intercept    -0.221664    0.801184
12                     Pets    -0.334218    0.715897

In [179]:
reg.score(x_test, y_test)

0.7357142857142858

In [182]:
predict_proba = reg.predict_proba(x_test)
predict_proba

array([[0.74194034, 0.25805966],
       [0.58867232, 0.41132768],
       [0.36700305, 0.63299695],
       [0.80970691, 0.19029309],
       [0.06067081, 0.93932919],
       [0.30614033, 0.69385967],
       [0.28812062, 0.71187938],
       [0.08332494, 0.91667506],
       [0.80794705, 0.19205295],
       [0.76096801, 0.23903199],
       [0.45671819, 0.54328181],
       [0.15647436, 0.84352564],
       [0.04443443, 0.95556557],
       [0.73037967, 0.26962033],
       [0.23072448, 0.76927552],
       [0.5577509 , 0.4422491 ],
       [0.53439626, 0.46560374],
       [0.54791901, 0.45208099],
       [0.38911594, 0.61088406],
       [0.02497015, 0.97502985],
       [0.69428594, 0.30571406],
       [0.80248596, 0.19751404],
       [0.38186907, 0.61813093],
       [0.39933351, 0.60066649],
       [0.17837581, 0.82162419],
       [0.75202224, 0.24797776],
       [0.46296834, 0.53703166],
       [0.89202337, 0.10797663],
       [0.13822132, 0.86177868],
       [0.79194308, 0.20805692],
       [0.

In [184]:
predict_proba.shape

(140, 2)

In [186]:
predict_proba[:,1]

array([0.25805966, 0.41132768, 0.63299695, 0.19029309, 0.93932919,
       0.69385967, 0.71187938, 0.91667506, 0.19205295, 0.23903199,
       0.54328181, 0.84352564, 0.95556557, 0.26962033, 0.76927552,
       0.4422491 , 0.46560374, 0.45208099, 0.61088406, 0.97502985,
       0.30571406, 0.19751404, 0.61813093, 0.60066649, 0.82162419,
       0.24797776, 0.53703166, 0.10797663, 0.86177868, 0.20805692,
       0.38856092, 0.71257791, 0.69916022, 0.56637861, 0.20054686,
       0.54019107, 0.2013801 , 0.81773408, 0.44150299, 0.61618117,
       0.21408797, 0.3953131 , 0.21354785, 0.09855519, 0.83762026,
       0.66173729, 0.72333631, 0.26445655, 0.19829772, 0.17469092,
       0.57609926, 0.08201449, 0.68772182, 0.28044145, 0.87172933,
       0.48497014, 0.93161742, 0.25270585, 0.08072794, 0.08101068,
       0.73097829, 0.66324534, 0.30708121, 0.860348  , 0.18226923,
       0.26330648, 0.01336913, 0.2176612 , 0.80892658, 0.31405009,
       0.20854749, 0.07215809, 0.93404181, 0.45792521, 0.65080

#save model 

In [188]:
import pickle

In [189]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [ ]:
# pickle the scaler file
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)